import {
  AlertCircle,
  ArrowRight,
  BadgeCheck,
  Bell,
  Bold,
  Box,
  Calendar,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  CircleUser,
  CircleX,
  ClipboardList,
  Clock,
  Code,
  Command,
  CreditCard,
  Crown,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  EyeOff,
  File,
  FileArchive,
  FileSpreadsheet,
  FileText,
  Folder,
  GalleryVerticalEnd,
  GripVertical,
  Image,
  Info,
  Italic,
  Landmark,
  Laptop,
  LayoutDashboard,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  MessageSquare,
  Minus,
  Moon,
  Music,
  Package,
  PanelLeft,
  Paperclip,
  Palette,
  Pencil,
  Phone,
  Pizza,
  Plus,
  Receipt,
  Search,
  Send,
  Settings,
  Share2,
  Slash,
  SlidersHorizontal,
  Sparkles,
  SquareKanban,
  Star,
  Store,
  Sun,
  SunMoon,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Type,
  Underline,
  Upload,
  User,
  UserPen,
  UserX,
  Users,
  Video,
  X,
  type LucideIcon
} from 'lucide-react';

export type Icon = LucideIcon;

/**
 * Registro central de ícones — fonte única de verdade.
 * Importe sempre como `import { Icons } from '@/components/icons'` e use `Icons.chave`.
 * Biblioteca: lucide-react.
 */
export const Icons = {
  // General
  alertCircle: AlertCircle,
  warning: TriangleAlert,
  arrowRight: ArrowRight,
  check: Check,
  checks: CheckCheck,
  circleCheck: CircleCheck,
  close: X,
  clock: Clock,
  code: Code,
  dots: Ellipsis,
  ellipsis: EllipsisVertical,
  externalLink: ExternalLink,
  help: CircleHelp,
  info: Info,
  spinner: LoaderCircle,
  search: Search,
  settings: Settings,
  trash: Trash2,

  // Navigation / Chevrons
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsDown: ChevronsDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUpDown: ChevronsUpDown,

  // Layout
  dashboard: LayoutDashboard,
  kanban: SquareKanban,
  panelLeft: PanelLeft,

  // User
  user: User,
  user2: CircleUser,
  account: CircleUser,
  profile: User,
  employee: UserX,
  userPen: UserPen,
  teams: Users,

  // Brand (lucide não traz ícones de marca — usa-se um ícone neutro)
  github: Code,
  twitter: Code,
  logo: Command,

  // Communication
  chat: MessageSquare,
  notification: Bell,
  phone: Phone,
  video: Video,
  send: Send,
  paperclip: Paperclip,

  // Files
  page: File,
  post: FileText,
  fileTypePdf: FileText,
  fileTypeDoc: FileText,
  fileTypeXls: FileSpreadsheet,
  fileZip: FileArchive,
  media: Image,
  music: Music,

  // Actions
  add: Plus,
  edit: Pencil,
  upload: Upload,
  share: Share2,
  login: LogIn,
  logout: LogOut,
  gripVertical: GripVertical,

  // Shapes / Indicators
  circle: Circle,
  circleX: CircleX,
  plusCircle: CirclePlus,
  xCircle: CircleX,
  minus: Minus,

  // Theme
  sun: Sun,
  moon: Moon,
  brightness: SunMoon,
  laptop: Laptop,
  palette: Palette,

  // Commerce / Plans
  billing: CreditCard,
  creditCard: CreditCard,
  product: Package,
  supplier: Store,
  costCenter: Landmark,
  catalog: ClipboardList,
  request: FileText,
  report: ChartColumn,
  receipt: Receipt,
  pro: Crown,
  exclusive: Star,
  sparkles: Sparkles,
  badgeCheck: BadgeCheck,
  lock: Lock,

  // Data / Charts
  trendingDown: TrendingDown,
  trendingUp: TrendingUp,
  eyeOff: EyeOff,
  adjustments: SlidersHorizontal,

  // Text formatting
  bold: Bold,
  italic: Italic,
  underline: Underline,
  text: Type,

  // Toast
  toastSuccess: CircleCheck,
  toastInfo: Info,
  toastWarning: TriangleAlert,
  toastError: CircleX,
  toastLoading: LoaderCircle,

  // Misc
  pizza: Pizza,
  workspace: Folder,
  forms: FileText,
  slash: Slash,
  calendar: Calendar,
  galleryVerticalEnd: GalleryVerticalEnd,
  moreHorizontal: Ellipsis,
  box: Box
};
